name: Markdown Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-check.yml"
      - ".markdownlint.json"

  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/markdown-check.yml"
      - ".markdownlint.json"

  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  markdown-check:
    name: Validate Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install markdownlint
        run: npm install --global markdownlint-cli2

      - name: Run markdownlint
        run: |
          markdownlint-cli2 \
            "**/*.md" \
            "#node_modules" \
            "#dist" \
            "#build"